export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_ALERT = "SET_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_FAIL = "AUTH_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const GET_PROFILE = "GET_PROFILE";

// Store
export const CREATE_STORE = "CREATE_STORE";
export const DELETE_STORE = "DELETE_STORE";
export const UPDATE_STORE = "UPDATE_STORE";
export const GET_STORE_POST = "GET_STORE_POST";
export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";
export const GET_STORE_COMMENTS = "GET_STORE_COMMENTS";
export const UPLOAD_STORE_IMAGE = "UPLOAD_STORE_IMAGE";
export const UPDATE_STORE_DETAILS = "UPDATE_STORE_DETAILS";
export const GET_STORE_BY_OWNER_ID = "GET_STORE_BY_OWNER_ID ";
export const GET_STORE_PROFILE_PHOTO = "GET_STORE_PROFILE_PHOTO";
